POST http://localhost:3000/api/tables
Content-Type: application/json

{
  "name": "Table 6",
  "capacity": 4
}

###
POST http://localhost:3000/api/layouts
Content-Type: application/json

{
  "tableId": "34b53011-81c1-4fad-b35a-086a91795f36",
  "positionX": 100,
  "positionY": 150
}

###
POST http://localhost:3000/api/layouts
Content-Type: application/json

{
  "tableId": "5049e5ce-c6af-4bf7-90e4-4db1dd92c50c",
  "positionX": 200,
  "positionY": 250
}

###
POST http://localhost:3000/api/layouts
Content-Type: application/json

{
  "positionX": 120,
  "positionY": 90
}

###
DELETE http://localhost:3000/api/layouts/2

###
PUT http://localhost:3000/api/layouts/1
Content-Type: application/json

{
  "tableId": "f5c7f595-2ea6-421c-9aff-1cf5c4669ab8",
  "content": "Hello world"
}

###
POST http://localhost:3000/api/tables/069f9ce0-5a68-4049-8049-230de623ae63/people
Content-Type: application/json

{
  "name": "Alice"
}